---

- name: update apt cache (if out of date)
  #Updates it only every 4 hours
  apt: update_cache=yes cache_valid_time={{ 60*60*4 }}
  sudo: true

- name: Make sure the ansible required dependencies are installed
  apt:
    pkg: python-pycurl
    state: present

- name: Add the git repository
  apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Install the git package
  apt:
    pkg: git
    state: present